env:
  browser: true
  es2021: true
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  semi:
    - error
    - always
  no-dupe-keys:
    - error
  no-empty:
    - error
  no-unreachable:
    - error
  eqeqeq:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
